[package]
name = "deck-application"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
libdj = { path = "../libdj" }
libdatabase = { path = "../libdatabase" }
libui = { path = "../libui" }

[lints]
workspace = true
