[package]
name = "godot-ui-code"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
interprocess = "2.4.0"
godot = "0.5.2"
thiserror.workspace = true
libdj = { path = "../libdj" }
libdsp = { path = "../libdsp" }
libdatabase = { path = "../libdatabase" }
libui = { path = "../libui" }
rkyv.workspace = true
base64.workspace = true

[lints]
workspace = true
