[package]
name = "libdatabase"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
netlink-sys = { version = "0.9.0", features = [ "tokio_socket" ] }
kobject-uevent = "0.2.0"
rekordcrate = { git = "https://github.com/FizzyApple12/rekordcrate.git", branch = "djdeck" }
binrw = "0.15"
libdj = { path = "../libdj" }
timecode = { path = "../timecode" }

[lints]
workspace = true
