[package]
name = "libdj"
version.workspace = true
edition.workspace = true

[dependencies]
rkyv.workspace = true
thiserror.workspace = true
tokio.workspace = true
num.workspace = true
criterion.workspace = true
cpal = { version = "0.18.2", features = [ "pipewire" ] }
midir = { version = "0.11.0", features = [ ] }
libdsp = { path = "../libdsp" }

alsa-sys.version = "0.4.0"
alsa.version = "0.11"

[lints]
workspace = true

# [[bench]]
# name = "audio_pipeline"
# harness = false
