[package]
name = "libdj"
version.workspace = true
edition.workspace = true

[dependencies]
rkyv.workspace = true
thiserror.workspace = true
tokio.workspace = true
pipewire = "0.9.2"
pipewire-sys = "0.9.2"
libspa-sys = "0.9.2"
cute-dsp = "0.0.40"
symphonia = { version = "0.5.5", features = ["opt-simd","all-codecs","all-formats"] }
symphonia-core = "0.5.5"
midir = "0.10.3"

[lints]
workspace = true
