[package]
name = "libdj"
version.workspace = true
edition.workspace = true

[dependencies]
rkyv.workspace = true
thiserror.workspace = true
tokio.workspace = true
cpal = { git = "https://github.com/RustAudio/cpal.git", features = [ "pipewire" ] }
midir = { version = "0.11.0", features = [ ] }
symphonia = { version = "0.5.5", features = [ "opt-simd", "all-codecs", "all-formats" ] }
symphonia-core = "0.5.5"
libdsp = { path = "../libdsp" }

alsa-sys.version = "0.4.0"
alsa.version = "0.11"

[lints]
workspace = true
