[package]
name = "libui"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
libdj = { path = "../libdj" }
libdsp = { path = "../libdsp" }
interprocess = { version = "2.4.0", features = ["tokio"] }
rkyv.workspace = true
base64.workspace = true

[lints]
workspace = true
